### PR TITLE
Finishing NYT Website Clone

### PR DESCRIPTION
**Pull request by MakZ**
Added fixed navbar on the bottom. I have added such a form at the bottom to comply with proper UX. I focused on the clone page to make it similar.

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: INVALID 🔴 🟥 

### Hey there, 👋🏽 

I'm invalidating this PR because the PR does not have a meaningful title and a brief description.
Kindly visit the lesson and master how to do this. [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/).

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work on this PR @MakZ and @mke2111 . 

- [x] Add `.vscode` folder to `.gitignore`. This folder exposes `settings` and `configurations` in the app. Committing it is not a good idea.
- [x] You lack a README file in this PR. It is mandatory to add one. Please use [this](https://github.com/microverseinc/readme-template) template for guidance.
- [x] The `div class='expand-button-text'>`EXPAND`</div>` is overlapping with `<div class='expand-text>'` ...`<div/>`. This is affecting the UX of the page. Add `margin-left` to `.expand-text-button` to give some room to the elements.
- [x] The original [page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0) has this:
Screenshot from 2021-02-17 13-11-02
But you have:
Screenshot from 2021-02-17 13-11-08
Did you access the right page? Make sure you didn't open the page in `cognito mode` as this would present to you a different page. Your design be similar to [this](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)
     #### Note: This section also has a video from youtube and `The Bicep2 telescope` image. Make sure to add those as well.
- [x] The text `Space & Cosmos` on the navbar must be a link same as `Subscribe Now` and `Log In` buttons on the far right corner. Please turn those into links.
- [x] The `Subscribe Now` and `Log In` buttons on the original page have a height of `32px` and a `border-radius` but you have a height of `40px` and no `border-radius`. Please fix that.
- [x] Your footer is not the same as the one on the original page.
This is on the original page:
Screenshot from 2021-02-17 13-24-17

This is what you have:
Screenshot from 2021-02-17 13-24-22

### Note: The main objective of this project is to use the concepts of positioning such as `float`, `grid` and `flex` to replicate the New York times article page. Make sure your design is the same as that of the original page.


### Martin Afani

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Maksymilian Zuzel** 
Good job with your first submission for this project :muscle:  :muscle:
Your page really looks like the original :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] Add a README file to your project
- [x] Add a Live Demo of your project, you might use the next tool (or you might use github pages): https://raw.githack.com/
- [x] In the navbar, The NY Times logo should be a link
- [x] In your CSS file, don't overuse !important
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by NtwaliHeritier — COMMENTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑**
Hello team, great work implementing the changes.
However the live link is kind of messed.
Github pages does that. As an alternative host to netlify as it solves the issue.
Solve that and ask for another review.
Happy coding💻

**Pull request merged**
